In [1]:
import pandas as pd

data = {
    'Hours_Studied': [1, 2, 3, 4, 5, 6, 7, 8, 2.5, 3.5, 5.5, 6.5],
    'Attendance': [50, 60, 65, 70, 75, 80, 85, 90, 55, 68, 78, 88],
    'Marks': [35, 40, 45, 50, 55, 65, 70, 80, 42, 48, 60, 72]
}

df = pd.DataFrame(data)
print(df)

    Hours_Studied  Attendance  Marks
0             1.0          50     35
1             2.0          60     40
2             3.0          65     45
3             4.0          70     50
4             5.0          75     55
5             6.0          80     65
6             7.0          85     70
7             8.0          90     80
8             2.5          55     42
9             3.5          68     48
10            5.5          78     60
11            6.5          88     72

In [2]:
x=df[["Hours_Studied"]]
y=df["Marks"]
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x,y)

LinearRegression()

In [3]:
model.predict([[9]])

C:\Users\PALLAVI H\miniconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([84.33012821])

In [4]:
model.coef_#slope(m)

array([6.48076923])

In [5]:
model.intercept_#intercept(c)

np.float64(26.003205128205124)

In [6]:
#y=(m*x)+c

In [7]:
(6.48076923*9)+26.003205128205124 #x=9

84.33012819820513

Multiple linear regression

In [8]:
df.head()

   Hours_Studied  Attendance  Marks
0            1.0          50     35
1            2.0          60     40
2            3.0          65     45
3            4.0          70     50
4            5.0          75     55

In [9]:
#feature selection
x=df[["Hours_Studied","Attendance"]]
y=df["Marks"]

In [10]:
from sklearn.linear_model import LinearRegression
model1=LinearRegression()
model1.fit(x,y)
model1.predict([[9,88]])

C:\Users\PALLAVI H\miniconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([83.04563111])

In [11]:
model1.coef_

array([5.75038072, 0.1251407 ])

In [12]:
model1.intercept_

np.float64(20.279822993224293)

In [13]:
model1.predict([[1,50]])

C:\Users\PALLAVI H\miniconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([32.28723874])

In [14]:
x=df[["Hours_Studied","Attendance"]]
y=df["Marks"]

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [17]:
print(x_train)

    Hours_Studied  Attendance
8             2.5          55
5             6.0          80
2             3.0          65
1             2.0          60
11            6.5          88
4             5.0          75
7             8.0          90
3             4.0          70
6             7.0          85

In [18]:
mlr=LinearRegression().fit(x_train,y_train)

In [19]:
y_pred=mlr.predict(x_test)
y_pred

array([61.85624547, 48.69893809, 30.96309207])

In [20]:
from sklearn.metrics import mean_squared_error,r2_score,mean_absolute_error

In [21]:
print("Error= ",mean_squared_error(y_pred,y_test))
print("R2 Score= ",r2_score(y_pred,y_test))
print("MAE= ",mean_absolute_error(y_pred,y_test))

Error=  6.7435957672980615
R2 Score=  0.957912790023541
MAE=  2.1973638291589452

In [22]:
import pandas as pd
data = {
    'Age': [25, 40, 35, 50, 23, 45, 52, 33],
    'Balance': [20000, 50000, 30000, 80000, 15000, 60000, 90000, 40000],
    'Active': [1, 0, 1, 0, 1, 0, 0, 1],
    'Churn': [0, 1, 0, 1, 0, 1, 1, 0]
}

df = pd.DataFrame(data)
df

   Age  Balance  Active  Churn
0   25    20000       1      0
1   40    50000       0      1
2   35    30000       1      0
3   50    80000       0      1
4   23    15000       1      0
5   45    60000       0      1
6   52    90000       0      1
7   33    40000       1      0

In [23]:
from sklearn.linear_model import LogisticRegression

In [24]:
a=LogisticRegression()

In [25]:
y=df["Churn"]

In [26]:
x=df[["Age","Balance","Active"]]

In [27]:
from sklearn.model_selection import train_test_split

In [28]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [29]:
print(x_train)

   Age  Balance  Active
7   33    40000       1
2   35    30000       1
4   23    15000       1
3   50    80000       0
6   52    90000       0

In [30]:
a.fit(x_train,y_train)

C:\Users\PALLAVI H\miniconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [31]:
y_pred=a.predict(x_test)
y_pred

array([0, 1, 0])

In [32]:
a.predict([[25,20000,1]])

C:\Users\PALLAVI H\miniconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])

In [33]:
a.predict([[50,79000,0]])

C:\Users\PALLAVI H\miniconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([1])

In [34]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [35]:
print("Accuracy= ",accuracy_score(y_test,y_pred))
print("Confusion_Matrix= \n",confusion_matrix(y_test,y_pred))
print("Classification_report= ",classification_report(y_test,y_pred))

Accuracy=  0.6666666666666666
Confusion_Matrix=
 [[1 0]
 [1 1]]
Classification_report=                precision    recall  f1-score   support

           0       0.50      1.00      0.67         1
           1       1.00      0.50      0.67         2

    accuracy                           0.67         3
   macro avg       0.75      0.75      0.67         3
weighted avg       0.83      0.67      0.67         3

In [36]:
import numpy as np

In [37]:
x=np.array([30,40000,1])

In [38]:
w=np.array([0.2,0.00001,0.5])

In [39]:
b=0.1

In [40]:
z=np.dot(x,w)+b
print("Weighted Sum is:",z)

Weighted Sum is: 7.0

In [41]:
#Activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-z))
output=sigmoid(z)
print("Neuron Output:",output)

Neuron Output: 0.9990889488055994

In [42]:
if(output>0.5):
    print("Churned")
else:
    print("Not churned")

Churned

In [43]:
import pandas as pd

data = {
    'Hours_Studied': [1, 2, 3, 4, 5, 6, 7, 8, 2.5, 3.5, 5.5, 6.5],
    'Attendance': [50, 60, 65, 70, 75, 80, 85, 90, 55, 68, 78, 88],
    'Marks': [35, 40, 45, 50, 55, 65, 70, 80, 42, 48, 60, 72]
}

df = pd.DataFrame(data)
print(df)

    Hours_Studied  Attendance  Marks
0             1.0          50     35
1             2.0          60     40
2             3.0          65     45
3             4.0          70     50
4             5.0          75     55
5             6.0          80     65
6             7.0          85     70
7             8.0          90     80
8             2.5          55     42
9             3.5          68     48
10            5.5          78     60
11            6.5          88     72

In [44]:
import numpy as  np

In [45]:
x=np.array([2,40])

In [46]:
w=np.array([0.1,0.2])

In [47]:
b=0.3

In [48]:
z=np.dot(x,w)+b
print("Weighted Sum is:",z)

Weighted Sum is: 8.5

In [49]:
def sigmoid(x):
    return 1 / (1 + np.exp(-z))
output=sigmoid(z)
print("Neuron Output:",output)

Neuron Output: 0.9997965730219448

In [50]:
w1=np.array([[0.5,0.2],
             [0.3,0.7]])
b1=np.array([1,1])
hidden=np.dot(w1,x)+b1
print("Hidden Layer Output:",hidden)

Hidden Layer Output: [10.  29.6]

In [51]:
w2=np.array([0.2,0.7])
h=np.dot(w2,x)+b1
print(h)

[29.4 29.4]

In [52]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
output=sigmoid(h)
print("Neuron Output:",output)

Neuron Output: [1. 1.]

In [57]:
import sys
print(sys.version)
print(sys.executable)
!pip --version

3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]
C:\Users\PALLAVI H\miniconda3\python.exe
pip 25.2 from C:\Users\PALLAVI H\miniconda3\Lib\site-packages\pip (python 3.13)

In [ ]:
!pip install tensorflow

In [63]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model=Sequential([
    Dense(10, activation='relu', input_shape=(2,)),
    Dense(5, activation='relu'),
    Dense(1, activation='sigmoid')
])
model.summary()

ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
import math
1/(1+math.exp(-1000))

In [ ]:
import numpy as np
1/(1+np.exp(-(1000)))

In [ ]:
import numpy as np

In [ ]:
def sigmoid(x):
    return 1 / (1 +np.exp(-x))
def tanh(x):
    return np.tanh(x)
def relu(x):
    return np.maximum(0,x)

In [ ]:
x=np.linspace(-10,10,100)
x

In [ ]:
s=np.array([-2,-3,0,1,18])
print("Sigmoid:",sigmoid(s))
print("TanH:",tanh(s))
print("Relu:",relu(s))

In [64]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_classification

In [65]:
X, y = make_classification(n_samples=1000, n_features=20, random_state=42)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print("Data Ready")

Data Ready